### PR TITLE
MNT Travis shared config

### PR DESCRIPTION
**Pull request by dnsl48**

### CODE REVIEW

**Comment by emteknetnz** [comment]
@dnsl48 

To fix the failing npm test https://travis-ci.com/github/silverstripe/silverstripe-segment-field/jobs/430882942

I think you can update package.json with "scripts" .. "test" > "echo 1 > /dev/null"

**Comment by dnsl48** [comment]
Apart from the missing js tests it looks like the compiled sourcemaps are different on Travis... I couldn't reproduce this locally so far.

**Comment by emteknetnz** [comment]
`which true` .. `/usr/bin/true`

today I learnt :-)

**Comment by emteknetnz** [comment]
you'll need to `yarn build` to fix that issue

**Pull request merged**
